# Generated by Django 5.0 on 2026-03-07 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default=None, max_length=10)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('term', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='student_app.term')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('reference', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.term')),
            ],
        ),
    ]
