# Generated by Django 5.0 on 2026-04-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('parent', 'parent'), ('teacher', 'teacher'), ('e_officer', 'exam efficer'), ('manager', 'manager'), ('s_principal', 'secondary principal'), ('p_principal', 'primary principal'), ('n_principal', 'nursery principal'), ('accountant', 'accountant')], default='parent', max_length=20),
        ),
    ]
