# Generated by Django 5.0 on 2026-02-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('parent', 'parent'), ('student', 'student'), ('manager', 'manager'), ('s_principal', 'secondary principal'), ('p_principal', 'primary principal'), ('accountant', 'accountant')], default='manager', max_length=20),
        ),
    ]
