# Generated by Django 5.0 on 2026-02-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_full_name_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('parent', 'parent'), ('student', 'student'), ('teacher', 'teacher'), ('manager', 'manager'), ('s_principal', 'secondary principal'), ('p_principal', 'primary principal'), ('accountant', 'accountant')], default='parent', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='img_root/'),
        ),
    ]
